use_field_init_shorthand = true
trailing_comma = "Never"
newline_style = "Unix"
hard_tabs = true
fn_call_width = 40

unstable_features = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
condense_wildcard_suffixes = true
