[package]
name = "starflow-util"
version = "0.0.1"
edition = "2024"

[features]
winit = ["dep:winit"]
wgpu = ["dep:wgpu"]

[dependencies]
winit = { workspace = true, optional = true }
wgpu = { workspace = true, optional = true }
