[package]
name = "starflow-window"
version = "0.0.1"
edition = "2024"

[dependencies]
glued = { workspace = true }
starflow-util = { workspace = true }

winit = { workspace = true }
default = "0.1.2"
log = "0.4.27"
