[package]
name = "starflow-render"
version = "0.1.0"
edition = "2024"

[dependencies]
glued = { path = "../../../glued" }
starflow-window = { path = "../window" }
starflow-util = { path = "../../shared/util", features = ["winit"]}

wgpu = "25.0.0"
default = "0.1.2"
